#include "RaceSyncUiPages.h"

const char RACESYNC_SESSIONS_UI[] PROGMEM = R"HTML(<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RaceSync</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#f4f6f8;background:#101418}*{box-sizing:border-box}body{margin:0}.wrap{max-width:920px;margin:auto;padding:18px}.head,.bar,.session,.priority{background:#192027;border:1px solid #2a343d;border-radius:12px;padding:16px;margin-bottom:12px}.head{display:flex;justify-content:space-between;align-items:center}.brand{font-size:26px;font-weight:800}.sub,.meta{color:#9ba8b4;font-size:13px}.status{font-size:13px;text-align:right}.ok{color:#75d69c}.warn{color:#ffca6b}.bar{display:flex;gap:10px;justify-content:space-between;align-items:center}.btn{border:0;border-radius:8px;padding:10px 13px;font-weight:700;cursor:pointer;background:#e9eef2;color:#111;text-decoration:none;display:inline-block}.primary{background:#54bdf5}.ghost{background:#303a43;color:#fff}.session{display:grid;grid-template-columns:1fr auto;gap:12px}.title{font-weight:750;font-size:16px}.timing{display:grid;grid-template-columns:repeat(4,minmax(100px,1fr));gap:8px;margin-top:10px}.timing div{background:#12181d;border-radius:8px;padding:8px}.timing b{display:block;font-size:11px;color:#87939e;margin-bottom:3px}.new{display:inline-block;background:#54bdf5;color:#071018;border-radius:12px;padding:2px 8px;font-size:11px;font-weight:800;margin-right:7px}.flag{font-size:15px;margin-right:7px}.actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.empty{text-align:center;color:#9ba8b4;padding:35px}.priority{text-align:center;border-color:#8d6c1d}.priority strong{display:block;font-size:22px;color:#ffca6b;margin-bottom:6px}.foot{color:#87939e;font-size:12px;text-align:center;padding:12px}.nav{margin-top:10px;display:flex;gap:14px;flex-wrap:wrap}.nav a{color:#54bdf5;text-decoration:none;font-size:13px}@media(max-width:650px){.session{grid-template-columns:1fr}.actions .btn{flex:1}.bar{align-items:stretch;flex-direction:column}.head{align-items:flex-start}.status{text-align:left;margin-top:10px}.timing{grid-template-columns:1fr 1fr}}
</style></head><body><main class="wrap">
<div class="head"><div><div class="brand">RaceSync</div><div class="sub">Motorcycle Data Logger</div><div class="nav"><a href="/control">Logging Control & Settings</a><a href="/status">Device Status</a></div></div><div class="status"><div id="gps">GPS ...</div><div id="sd">Storage ...</div><div id="rpm">RPM ...</div><div id="log">Logger ...</div></div></div>
<div id="priority" class="priority" style="display:none"><strong>● RECORDING</strong><div id="priorityText">Race-priority mode active</div></div>
<div id="sessionArea"><div class="bar"><div><strong>Stored Sessions</strong><div class="sub" id="summary">Loading...</div></div><button class="btn primary" id="all" onclick="downloadAllNew()">Download All New</button></div><div id="sessions"></div></div>
<div class="foot" id="footer">RaceSync</div></main>
<script>
const key='racesync_downloaded_sessions';let sessions=[],wasRecording=false;const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
function downloaded(){try{return new Set(JSON.parse(localStorage.getItem(key)||'[]').map(String))}catch(e){return new Set()}}
function mark(id){const s=downloaded();s.add(String(id));localStorage.setItem(key,JSON.stringify([...s]));render()}
function fmt(n){if(n==null)return '';if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function parts(file){const m=String(file).match(/^RS_(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})\.vbo$/i);return m?{y:+m[1],mo:+m[2],d:+m[3],h:+m[4],mi:+m[5],s:+m[6]}:null}
function stamp(s){if(s.startTime&&/^\d{4}-/.test(s.startTime)){const t=Date.parse(s.startTime);if(Number.isFinite(t))return t}const p=parts(s.file);return p?Date.UTC(p.y,p.mo-1,p.d,p.h,p.mi,p.s):0}
function sortSessions(list){return [...list].sort((a,b)=>stamp(b)-stamp(a)||String(b.file).localeCompare(String(a.file)))}
function fallbackStart(file){const p=parts(file);if(!p)return {date:'Unknown',time:'—'};return {date:String(p.d).padStart(2,'0')+' '+months[p.mo-1]+' '+p.y,time:String(p.h).padStart(2,'0')+':'+String(p.mi).padStart(2,'0')+':'+String(p.s).padStart(2,'0')}}
function dt(v){if(!v)return null;const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})/);if(!m)return null;return {date:m[3]+' '+months[Number(m[2])-1]+' '+m[1],time:m[4]+':'+m[5]+':'+m[6]}}
function elapsed(sec){if(sec==null||!Number.isFinite(Number(sec)))return '—';sec=Math.max(0,Math.round(Number(sec)));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return (h?h+'h ':'')+(m?m+'m ':'')+s+'s'}
function render(){const seen=downloaded(),box=document.getElementById('sessions');const complete=sessions.filter(s=>s.complete),fresh=complete.filter(s=>!seen.has(String(s.id)));document.getElementById('summary').textContent=complete.length+' sessions · '+fresh.length+' new · newest first';document.getElementById('all').disabled=!fresh.length;box.innerHTML=sessions.length?'':'<div class="empty">No stored sessions</div>';sessions.forEach(s=>{const isNew=!seen.has(String(s.id))&&s.complete,start=dt(s.startTime)||fallbackStart(s.file),end=dt(s.endTime),d=document.createElement('div');d.className='session';d.innerHTML='<div><div class="title">'+(s.successful?'<span class="flag" title="Completed recording">🏁</span>':'')+(isNew?'<span class="new">NEW</span>':'')+esc(s.file)+'</div><div class="timing"><div><b>DATE</b>'+esc(start.date)+'</div><div><b>START</b>'+esc(start.time)+'</div><div><b>END</b>'+esc(end?end.time:'—')+'</div><div><b>ELAPSED</b>'+esc(elapsed(s.elapsedSeconds))+'</div></div><div class="meta" style="margin-top:8px">'+fmt(s.sizeBytes)+'</div></div><div class="actions"><button class="btn primary">Download VBO</button>'+(s.hasKml?'<button class="btn ghost">Generate KML</button>':'')+'</div>';const b=d.querySelectorAll('button');let i=0;b[i++].onclick=()=>dl(s.downloadUrl,s.id);if(s.hasKml)b[i++].onclick=()=>dl(s.kmlDownloadUrl,s.id);box.appendChild(d)})}
function dl(url,id){const a=document.createElement('a');a.href=url;a.click();mark(id)}
function downloadAllNew(){const seen=downloaded(),fresh=sessions.filter(s=>s.complete&&!seen.has(String(s.id)));fresh.forEach((s,i)=>setTimeout(()=>dl(s.downloadUrl,s.id),i*600))}
async function loadSessions(){const r=await fetch('/api/session-summaries',{cache:'no-store'});if(!r.ok)return;sessions=sortSessions((await r.json()).sessions||[]);render()}
async function tick(){try{const rr=await fetch('/api/runtime',{cache:'no-store'}),r=await rr.json(),rec=!!r.recording;document.getElementById('gps').innerHTML='<span class="'+(r.gpsValid?'ok':'warn')+'">●</span> GPS '+(r.gpsValid?'READY':'WAITING');document.getElementById('sd').innerHTML='<span class="'+(r.storageReady?'ok':'warn')+'">●</span> '+(r.storageReady?'STORAGE READY':'STORAGE ERROR');document.getElementById('rpm').textContent='RPM '+Math.max(0,Math.round(Number(r.rpm||0))).toLocaleString();document.getElementById('log').textContent=rec?'● RECORDING':'Logger idle';document.getElementById('priority').style.display=rec?'block':'none';document.getElementById('sessionArea').style.display=rec?'none':'block';if(rec){document.getElementById('priorityText').innerHTML=(r.manual?'Manual test session · <a href="/control" style="color:#54bdf5">Stop available in Control</a>':'Automatic race session · web storage activity suspended')+' · '+elapsed(r.recordingSeconds);document.getElementById('footer').textContent='Race-priority mode · VBO logging has precedence';}else{document.getElementById('footer').textContent='RaceSync';if(wasRecording||!sessions.length)await loadSessions()}wasRecording=rec}catch(e){document.getElementById('log').textContent='Logger offline'}}
tick();setInterval(tick,2000);
</script></body></html>)HTML";
