#include "RaceSyncUiPages.h"

const char RACESYNC_CONTROL_UI[] PROGMEM = R"HTML(<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RaceSync Control</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#f4f6f8;background:#101418}*{box-sizing:border-box}body{margin:0}.wrap{max-width:940px;margin:auto;padding:18px}.panel{background:#192027;border:1px solid #2a343d;border-radius:12px;padding:18px;margin-bottom:14px}.head,.sectionHead{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.title{font-size:25px;font-weight:800}.nav{display:flex;gap:12px;flex-wrap:wrap}.link{color:#54bdf5;text-decoration:none}.sectionHead{margin-bottom:14px}.sectionHead h3{margin:0;font-size:18px}.help{color:#9ba8b4;font-size:13px;line-height:1.45;max-width:570px}.grid2,.grid3{display:grid;gap:10px}.grid2{grid-template-columns:repeat(2,minmax(0,1fr))}.grid3{grid-template-columns:repeat(3,minmax(0,1fr))}.card,.field{background:#12181d;border:1px solid #242f38;border-radius:10px;padding:12px}.label{display:block;color:#87939e;font-size:11px;font-weight:800;letter-spacing:.04em;margin-bottom:5px}.value{font-size:18px;font-weight:800}.rpmValue{font-size:34px;font-weight:850}.ok{color:#75d69c}.warn{color:#ffca6b}.bad{color:#ff8c8c}.btn,input{border:0;border-radius:9px;padding:11px;font-size:15px}.btn{font-weight:800;cursor:pointer;margin:4px 5px 4px 0}.btn:disabled,input:disabled{opacity:.45;cursor:not-allowed}.start{background:#75d69c;color:#07150c}.stop{background:#e76b6b;color:#190707}.save{background:#54bdf5;color:#071018}.reboot{background:#ffca6b;color:#171005}.secondary{background:#303a43;color:#fff}.field input{width:100%;margin-top:7px;background:#eef2f5;color:#111}.note{color:#87939e;font-size:12px;line-height:1.4;margin-top:7px}.actions{margin-top:14px}.notice{margin-top:10px;padding:10px 12px;border-radius:8px;background:#12181d;color:#9ba8b4;font-size:13px;min-height:39px}.toggleRow{display:flex;align-items:center;justify-content:space-between;gap:16px;background:#12181d;border:1px solid #242f38;border-radius:10px;padding:13px;margin-top:12px}.toggleRow input{width:21px;height:21px}.small{font-size:12px;color:#87939e}.dangerPanel{border-color:#5c4620}@media(max-width:700px){.head,.sectionHead{flex-direction:column}.grid2,.grid3{grid-template-columns:1fr}.wrap{padding:12px}}
</style></head><body><main class="wrap">
<div class="panel"><div class="head"><div><div class="title">RaceSync Control & Settings</div><div class="help">Configure logging, check device readiness and calibrate the throttle-position sensor.</div></div><div class="nav"><a class="link" href="/">Sessions</a><a class="link" href="/status">Device Status</a></div></div></div>

<div class="panel"><div class="sectionHead"><h3>Current status</h3><div class="help">Before riding, confirm GPS and storage are ready. Automatic logging will not arm until GPS data is valid.</div></div><div class="grid2"><div class="card"><span class="label">LOGGER</span><span class="value" id="state">Loading...</span></div><div class="card"><span class="label">GPS</span><span class="value" id="gpsState">Checking...</span><div class="small" id="gpsDetail"></div></div><div class="card"><span class="label">STORAGE</span><span class="value" id="storageState">Checking...</span></div></div><div id="details" class="small" style="margin-top:10px"></div></div>

<div class="panel"><div class="sectionHead"><h3>Manual logging</h3><div class="help">For stationary bench tests and sensor checks. A valid GPS fix is required to create a session. Manual sessions can be stopped here.</div></div><button class="btn start" id="start" onclick="startManual()">Start Manual Logging</button><button class="btn stop" id="stop" onclick="stopManual()">Stop Manual Logging</button><div id="notice" class="notice">Ready.</div></div>

<div class="panel"><div class="sectionHead"><h3>Automatic race logging</h3><div class="help">Recording starts from GPS movement and ends after the stationary delay. These controls are locked while recording.</div></div><div class="grid2"><label class="field"><span class="label">START SPEED (KM/H)</span><input id="speed" type="number" min="1" max="100" step="0.5"><div class="note">Speed must reach this value after GPS validity, freshness and satellite checks pass.</div></label><label class="field"><span class="label">STOP DELAY (SECONDS)</span><input id="delay" type="number" min="1" max="600"><div class="note">Time below the fixed stop-speed threshold before RaceSync closes the file.</div></label></div><div class="actions"><button class="btn save" id="save" onclick="saveSettings()">Save Automatic Logging Settings</button></div></div>

<div class="panel"><div class="sectionHead"><h3>Throttle position — setup &amp; calibration</h3><div class="help">GPIO1 reads the 0–3.3 V TPS signal at 200 Hz. Calibrate with the engine stopped and logging idle. Calibration is retained after reboot.</div></div>
<div class="grid3"><div class="card"><span class="label">THROTTLE</span><span class="rpmValue" id="tpsPercent">--</span><span class="small"> %</span></div><div class="card"><span class="label">RAW / FILTERED ADC</span><span class="value" id="tpsRaw">--</span><div class="note">12-bit ADC counts on GPIO <span id="tpsPin">1</span>.</div></div><div class="card"><span class="label">SENSOR STATUS</span><span class="value" id="tpsStatus">Checking...</span><div class="small" id="tpsCalibration"></div></div></div>
<ol class="help" style="max-width:none"><li>Switch the ignition on with the engine stopped and leave the throttle completely closed.</li><li>Select <strong>Capture closed throttle</strong>.</li><li>Hold the throttle fully open against the carburettor stop—do not force the sensor or linkage.</li><li>Select <strong>Capture full throttle</strong>, release it, then confirm the live value returns close to 0% and reaches close to 100%.</li></ol>
<div class="actions"><button class="btn save tpsAction" onclick="calibrateThrottle('closed')">1. Capture Closed Throttle</button><button class="btn save tpsAction" onclick="calibrateThrottle('open')">2. Capture Full Throttle</button><button class="btn secondary tpsAction" onclick="calibrateThrottle('clear')">Clear Calibration</button></div><div class="notice" id="tpsNotice">Calibration required after installation or any linkage adjustment.</div></div>

<div class="panel dangerPanel"><div class="sectionHead"><h3>Restart RaceSync</h3><div class="help">Reboots the ESP32. Disabled while recording so an active session cannot be interrupted.</div></div><button class="btn reboot" id="reboot" onclick="rebootDevice()">Reboot ESP32</button></div>
</main><script>
let settingsLoaded=false,busy=false;
function n(v){return Number(v||0)}function f(v){return Math.max(0,Math.round(n(v))).toLocaleString()}
function setNotice(text,error=false){const x=document.getElementById('notice');x.textContent=text;x.style.color=error?'#ff8c8c':'#9ba8b4'}
async function command(url){if(busy)return;busy=true;try{const r=await fetch(url,{method:'POST'}),x=await r.json();if(r.ok&&x.started)setNotice(x.cameraVideoStartQueued?'Logging started; GoPro video start queued':'Logging started; GoPro video not started: '+(x.cameraError||'camera not connected'),!x.cameraVideoStartQueued);else setNotice(r.ok?'Command successful':(x.error||'Command failed'),!r.ok)}catch(e){setNotice('Unable to contact RaceSync',true)}busy=false;await tick()}
function startManual(){command('/api/logging/start')}function stopManual(){command('/api/logging/stop')}
async function saveSettings(){if(busy)return;busy=true;try{const r=await fetch('/api/settings/logging',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({startSpeedKmh:Number(document.getElementById('speed').value),stopDelaySeconds:Number(document.getElementById('delay').value)})}),x=await r.json();setNotice(r.ok?'Automatic logging settings saved':(x.error||'Unable to save settings'),!r.ok)}catch(e){setNotice('Unable to save settings',true)}busy=false}
async function calibrateThrottle(position){if(busy)return;const prompts={closed:'Confirm the throttle is fully closed and the engine is stopped.',open:'Hold the throttle fully open against the carburettor stop.',clear:'Clear the saved throttle calibration?'};if(!confirm(prompts[position]))return;busy=true;const notice=document.getElementById('tpsNotice');try{const r=await fetch('/api/settings/throttle/calibrate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({position})}),x=await r.json();notice.textContent=r.ok?(position==='clear'?'Calibration cleared':'Captured '+position+' position'):(x.error||'Calibration failed');notice.style.color=r.ok?'#75d69c':'#ff8c8c'}catch(e){notice.textContent='Unable to contact RaceSync';notice.style.color='#ff8c8c'}busy=false}
async function rebootDevice(){if(confirm('Reboot RaceSync now?'))await fetch('/api/reboot',{method:'POST'})}
async function loadSettings(){if(!settingsLoaded){try{const s=await fetch('/api/settings/logging',{cache:'no-store'}),x=await s.json();document.getElementById('speed').value=x.startSpeedKmh;document.getElementById('delay').value=x.stopDelaySeconds;settingsLoaded=true}catch(e){}}}
async function tick(){try{const rr=await fetch('/api/runtime',{cache:'no-store'}),r=await rr.json(),rec=!!r.recording,manual=!!r.manual;const td=r.throttleDiagnostics||{};document.getElementById('state').textContent=rec?(manual?'MANUAL RECORDING':'AUTOMATIC RECORDING'):'IDLE';document.getElementById('state').className='value '+(rec?'warn':'ok');document.getElementById('gpsState').textContent=r.gpsValid?'READY':'WAITING';document.getElementById('gpsState').className='value '+(r.gpsValid?'ok':'warn');document.getElementById('gpsDetail').textContent=(r.satellites??0)+' satellites';document.getElementById('storageState').textContent=r.storageReady&&r.storageWritable?'READY':'NOT READY';document.getElementById('storageState').className='value '+(r.storageReady&&r.storageWritable?'ok':'bad');document.getElementById('tpsPercent').textContent=n(td.percent).toFixed(1);document.getElementById('tpsRaw').textContent=f(td.raw)+' / '+f(td.filteredRaw);document.getElementById('tpsPin').textContent=td.inputPin??1;document.getElementById('tpsStatus').textContent=!td.connected?'CHECK WIRING':(td.calibrated?'READY':'CALIBRATE');document.getElementById('tpsStatus').className='value '+(td.connected&&td.calibrated?'ok':'warn');document.getElementById('tpsCalibration').textContent='closed '+f(td.closedRaw)+' · open '+f(td.openRaw);document.getElementById('details').textContent=rec?(r.recordingSeconds+' s · '+r.samplesWritten+' samples · '+(manual?'manual':'automatic')+' session'):'Logger idle';document.getElementById('start').disabled=rec||!r.gpsValid||!r.storageReady;document.getElementById('stop').disabled=!rec;document.getElementById('save').disabled=rec;document.querySelectorAll('.tpsAction').forEach(x=>x.disabled=rec);document.getElementById('reboot').disabled=rec;document.getElementById('speed').disabled=rec;document.getElementById('delay').disabled=rec;if(rec&&!manual)setNotice('Automatic session: Stop Logging is available only with fresh GPS at or below the stationary threshold.');if(!rec)await loadSettings();setTimeout(tick,rec?1000:500)}catch(e){document.getElementById('state').textContent='OFFLINE';setTimeout(tick,1000)}}
tick();
</script></body></html>)HTML";
