#include "RaceSyncUiPages.h"

const char RACESYNC_CAMERA_UI[] PROGMEM = R"HTML(<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RaceSync Camera</title><style>:root{font-family:system-ui,-apple-system,sans-serif;color:#f4f6f8;background:#101418}body{margin:0}.wrap{max-width:820px;margin:auto;padding:18px}.panel{background:#192027;border:1px solid #2a343d;border-radius:12px;padding:16px;margin-bottom:12px}.btn{border:0;border-radius:8px;padding:10px 14px;margin:4px;font-weight:700;background:#2f7d4a;color:#fff}.btn.alt{background:#a33b3b}.btn.dim{background:#3c4852}.btn:disabled{opacity:.45}.nav{color:#fff;text-decoration:none;margin-right:12px}.warn{color:#ffd479}.ok{color:#8ee2a8}pre{white-space:pre-wrap;word-break:break-word;color:#dbe7ef}</style></head><body><main class="wrap"><div class="panel"><h2>GoPro HERO9 Bluetooth</h2><a class="nav" href="/">Sessions</a><a class="nav" href="/status">Status</a><a class="nav" href="/control">Control</a></div><div class="panel"><p class="warn">Bench-test feature: Bluetooth is off at boot and is never connected automatically. Disconnect the camera before riding.</p><button class="btn" id="connect" onclick="command('connect')">Enable Bluetooth &amp; Connect</button><button class="btn dim" id="refresh" onclick="command('refresh')">Refresh status</button><button class="btn alt" id="disconnect" onclick="command('disconnect')">Disconnect</button><p id="notice">Loading…</p><pre id="status"></pre></div></main><script>
let busy=false;
async function load(){try{const r=await fetch('/api/camera',{cache:'no-store'}),j=await r.json();show(j,r.ok)}catch(e){document.getElementById('notice').textContent='RaceSync unavailable'}}
function show(j,ok){document.getElementById('status').textContent=JSON.stringify(j,null,2);document.getElementById('notice').textContent=j.commandsAllowed===false?'Camera controls disabled while logging':(j.connected?'GoPro connected':j.state||'Disconnected');document.getElementById('notice').className=j.connected?'ok':'warn';document.getElementById('connect').disabled=busy||j.commandsAllowed===false||j.connected;document.getElementById('refresh').disabled=busy||j.commandsAllowed===false||!j.connected;document.getElementById('disconnect').disabled=busy||j.commandsAllowed===false||!j.connected}
async function command(action){busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);document.getElementById('notice').textContent=action==='connect'?'Scanning for GoPro…':'Working…';try{const r=await fetch('/api/camera/'+action,{method:'POST'}),j=await r.json();show(j,r.ok)}catch(e){document.getElementById('notice').textContent='Command failed'}busy=false;setTimeout(load,500)}
load();setInterval(()=>{if(!busy)load()},2000);
</script></body></html>)HTML";
