#include "RaceSyncApi.h"

namespace {
const char RACESYNC_UI[] PROGMEM = R"HTML(<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RaceSync</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#f4f6f8;background:#101418}*{box-sizing:border-box}body{margin:0}.wrap{max-width:900px;margin:auto;padding:18px}.head,.bar,.session{background:#192027;border:1px solid #2a343d;border-radius:12px;padding:16px;margin-bottom:12px}.head{display:flex;justify-content:space-between;align-items:center}.brand{font-size:26px;font-weight:800}.sub{color:#9ba8b4;font-size:13px}.status{font-size:13px;text-align:right}.ok{color:#75d69c}.warn{color:#ffca6b}.bar{display:flex;gap:10px;justify-content:space-between;align-items:center}.btn{border:0;border-radius:8px;padding:10px 13px;font-weight:700;cursor:pointer;background:#e9eef2;color:#111}.primary{background:#54bdf5}.danger{background:#e76b6b}.ghost{background:#303a43;color:#fff}.session{display:grid;grid-template-columns:1fr auto;gap:12px}.title{font-weight:750;font-size:16px}.meta{font-size:13px;color:#9ba8b4;margin-top:5px}.new{display:inline-block;background:#54bdf5;color:#071018;border-radius:12px;padding:2px 8px;font-size:11px;font-weight:800;margin-right:7px}.done{color:#75d69c;font-size:12px;margin-right:7px}.actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.empty{text-align:center;color:#9ba8b4;padding:35px}.foot{color:#87939e;font-size:12px;text-align:center;padding:12px}.nav{margin-top:10px;display:flex;gap:14px;flex-wrap:wrap}.nav a{color:#54bdf5;text-decoration:none;font-size:13px}@media(max-width:650px){.session{grid-template-columns:1fr}.actions .btn{flex:1}.bar{align-items:stretch;flex-direction:column}.head{align-items:flex-start}.status{text-align:left;margin-top:10px}}
</style></head><body><main class="wrap">
<div class="head"><div><div class="brand">RaceSync</div><div class="sub">Motorcycle Data Logger</div><div class="nav"><a href="/control">Logging Control & Settings</a><a href="/status">Full Device Status</a></div></div><div class="status"><div id="gps">GPS ...</div><div id="sd">Storage ...</div><div id="log">Logger ...</div></div></div>
<div class="bar"><div><strong>Stored Sessions</strong><div class="sub" id="summary">Loading...</div></div><button class="btn primary" id="all" onclick="downloadAllNew()">Download All New</button></div>
<div id="sessions"></div><div class="foot" id="footer">RaceSync</div></main>
<script>
const key='racesync_downloaded_sessions';let sessions=[];const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
function downloaded(){try{return new Set(JSON.parse(localStorage.getItem(key)||'[]').map(String))}catch(e){return new Set()}}
function mark(id){const s=downloaded();s.add(String(id));localStorage.setItem(key,JSON.stringify([...s]));render()}
function fmt(n){if(n==null)return '';if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function sessionParts(file){let m=String(file).match(/^RS_(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})\.vbo$/i);if(!m)m=String(file).match(/^RS_(\d{4})(\d{2})(\d{2})_(\d{2})(\d{2})(\d{2})\.vbo$/i);if(!m)return null;return {y:+m[1],mo:+m[2],d:+m[3],h:+m[4],mi:+m[5],s:+m[6]}}
function sessionStamp(file){const p=sessionParts(file);return p?Date.UTC(p.y,p.mo-1,p.d,p.h,p.mi,p.s):0}
function sessionDate(file){const p=sessionParts(file);if(!p)return file.replace(/\.vbo$/i,'').replace(/^RS_/,'');return p.d+' '+months[p.mo-1]+' '+p.y+' · '+String(p.h).padStart(2,'0')+':'+String(p.mi).padStart(2,'0')+':'+String(p.s).padStart(2,'0')+' UTC'}
function sortSessions(list){return [...list].sort((a,b)=>{const ta=sessionStamp(a.file),tb=sessionStamp(b.file);if(ta||tb)return tb-ta;return String(b.file).localeCompare(String(a.file))})}
function render(){const seen=downloaded(),box=document.getElementById('sessions');const complete=sessions.filter(s=>s.complete);const fresh=complete.filter(s=>!seen.has(String(s.id)));document.getElementById('summary').textContent=complete.length+' sessions · '+fresh.length+' new · newest first';document.getElementById('all').disabled=!fresh.length;box.innerHTML=sessions.length?'':'<div class="empty">No stored sessions</div>';sessions.forEach(s=>{const isNew=!seen.has(String(s.id))&&s.complete;const d=document.createElement('div');d.className='session';d.innerHTML='<div><div class="title">'+(isNew?'<span class="new">NEW</span>':'<span class="done">✓</span>')+esc(sessionDate(s.file))+'</div><div class="meta">'+esc(s.file)+' · '+fmt(s.sizeBytes)+(s.active?' · RECORDING':'')+'</div></div><div class="actions"><button class="btn primary">Download VBO</button>'+(s.hasKml?'<button class="btn ghost">Download KML</button>':'')+(s.deletable?'<button class="btn danger">Delete</button>':'')+'</div>';const b=d.querySelectorAll('button');let i=0;b[i++].onclick=()=>dl(s.downloadUrl,s.id);if(s.hasKml)b[i++].onclick=()=>dl(s.kmlDownloadUrl,s.id);if(s.deletable)b[i++].onclick=()=>del(s);box.appendChild(d)})}
function dl(url,id){const a=document.createElement('a');a.href=url;a.click();mark(id)}
async function del(s){if(!confirm('Delete '+s.file+' and its matching KML file?'))return;const r=await fetch(s.deleteUrl,{method:'DELETE'});if(!r.ok){alert('Unable to delete session');return}await load()}
function downloadAllNew(){const seen=downloaded();const fresh=sessions.filter(s=>s.complete&&!seen.has(String(s.id)));fresh.forEach((s,i)=>setTimeout(()=>dl(s.downloadUrl,s.id),i*600))}
async function load(){try{const [sr,st]=await Promise.all([fetch('/api/sessions',{cache:'no-store'}),fetch('/api/status',{cache:'no-store'})]);const sj=await sr.json(),x=await st.json();sessions=sortSessions(sj.sessions||[]);document.getElementById('gps').innerHTML='<span class="'+(x.gps&&x.gps.validFix?'ok':'warn')+'">●</span> GPS '+(x.gps&&x.gps.validFix?'READY':'WAITING');document.getElementById('sd').innerHTML='<span class="'+(x.storage&&x.storage.ready?'ok':'warn')+'">●</span> '+(x.storage&&x.storage.ready?'STORAGE READY':'STORAGE ERROR');document.getElementById('log').textContent=x.logger&&x.logger.recording?'● RECORDING':'Logger idle';document.getElementById('footer').textContent=fmt(x.storage.freeBytes)+' free · '+(x.system.firmware||'RaceSync');render()}catch(e){document.getElementById('summary').textContent='Unable to contact RaceSync'}}
load();setInterval(load,5000);
</script></body></html>)HTML";

const char RACESYNC_STATUS_UI[] PROGMEM = R"HTML(<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RaceSync Device Status</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#f4f6f8;background:#101418}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1050px;margin:auto;padding:18px}.head,.panel{background:#192027;border:1px solid #2a343d;border-radius:12px;padding:16px;margin-bottom:12px}.head{display:flex;justify-content:space-between;align-items:center;gap:12px}.brand{font-size:25px;font-weight:800}.sub{color:#9ba8b4;font-size:13px}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{display:inline-block;border:0;border-radius:8px;padding:9px 12px;font-weight:700;background:#303a43;color:#fff;text-decoration:none;cursor:pointer}.primary{background:#54bdf5;color:#071018}.stamp{font-size:12px;color:#87939e;margin-bottom:10px}pre{margin:0;white-space:pre-wrap;word-break:break-word;font:13px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;color:#dbe7ef}.error{color:#ff8c8c}@media(max-width:650px){.head{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="wrap">
<div class="head"><div><div class="brand">RaceSync Device Status</div><div class="sub">Complete contents of <code>/api/status</code></div></div><div class="actions"><a class="btn" href="/">Sessions</a><a class="btn" href="/control">Logging Control & Settings</a><button class="btn primary" onclick="loadStatus()">Refresh</button></div></div>
<div class="panel"><div class="stamp" id="stamp">Loading status...</div><pre id="status">Loading...</pre></div>
</main><script>
async function loadStatus(){const box=document.getElementById('status'),stamp=document.getElementById('stamp');try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const x=await r.json();box.className='';box.textContent=JSON.stringify(x,null,2);stamp.textContent='Last updated: '+new Date().toLocaleTimeString()}catch(e){box.className='error';box.textContent='Unable to read device status: '+e.message;stamp.textContent='Status unavailable'}}
loadStatus();setInterval(loadStatus,5000);
</script></body></html>)HTML";

const char RACESYNC_CONTROL_UI[] PROGMEM = R"HTML(<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RaceSync Logging Control</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#f4f6f8;background:#101418}*{box-sizing:border-box}body{margin:0}.wrap{max-width:760px;margin:auto;padding:18px}.head,.panel{background:#192027;border:1px solid #2a343d;border-radius:12px;padding:18px;margin-bottom:12px}.head{display:flex;justify-content:space-between;align-items:center;gap:12px}.brand{font-size:25px;font-weight:800}.sub{color:#9ba8b4;font-size:13px}.nav{display:flex;gap:8px;flex-wrap:wrap}.link{display:inline-block;border-radius:8px;padding:9px 12px;font-weight:700;background:#303a43;color:#fff;text-decoration:none}.state{text-align:center;padding:20px 10px}.stateName{font-size:34px;font-weight:850;margin:5px 0}.ok{color:#75d69c}.warn{color:#ffca6b}.bad{color:#ff8c8c}.details{color:#9ba8b4;font-size:14px;line-height:1.7}.controls{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.btn{border:0;border-radius:12px;padding:15px 14px;font-size:16px;font-weight:850;cursor:pointer}.start{background:#75d69c;color:#07130b}.stop{background:#e76b6b;color:#190707}.save{background:#54bdf5;color:#071018}.reboot{background:#ffca6b;color:#1d1504}.btn:disabled{opacity:.35;cursor:not-allowed}.notice{margin-top:14px;min-height:22px;text-align:center;font-size:14px}.info{margin-top:16px;padding:14px;border-radius:10px;background:#12181d;color:#9ba8b4;font-size:13px;line-height:1.55}.settingGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.field label{display:block;color:#dbe7ef;font-size:13px;font-weight:700;margin-bottom:6px}.field input{width:100%;border:1px solid #38444f;border-radius:9px;background:#101418;color:#fff;padding:11px;font-size:16px}.sectionTitle{font-size:18px;font-weight:800}.muted{color:#87939e;font-size:12px;margin-top:6px}.systemRow{display:flex;gap:12px;align-items:center;justify-content:space-between}.systemRow>div{max-width:520px}@media(max-width:560px){.head{align-items:flex-start;flex-direction:column}.controls,.settingGrid{grid-template-columns:1fr}.btn{padding:18px 14px}.systemRow{align-items:stretch;flex-direction:column}}
</style></head><body><main class="wrap">
<div class="head"><div><div class="brand">Logging Control & Settings</div><div class="sub">RaceSync configuration</div></div><div class="nav"><a class="link" href="/">Sessions</a><a class="link" href="/status">Status</a></div></div>

<div class="panel"><div class="state"><div class="sub">LOGGER</div><div class="stateName" id="state">Loading...</div><div class="details" id="details">Reading RaceSync status</div></div><div class="controls"><button class="btn start" id="start" onclick="startLogging()">Start Manual Logging</button><button class="btn stop" id="stop" onclick="stopLogging()">Stop Logging</button></div><div class="notice" id="notice"></div><div class="info">Manual start requires a valid GPS fix and ready storage. A manually started session ignores automatic stop timing until Stop Logging is pressed.</div></div>

<div class="panel"><div class="sectionTitle">Automatic Logging</div><div class="sub">These settings are saved in the ESP32 and retained after a reboot.</div><div class="settingGrid"><div class="field"><label for="startSpeed">Start recording above (km/h)</label><input id="startSpeed" type="number" min="1" max="100" step="0.5"><div class="muted">1–100 km/h</div></div><div class="field"><label for="stopDelay">End session after stopped for (seconds)</label><input id="stopDelay" type="number" min="1" max="600" step="1"><div class="muted">1–600 seconds. Stop threshold remains 3 km/h.</div></div></div><div class="controls" style="grid-template-columns:1fr"><button class="btn save" id="saveSettings" onclick="saveSettings()">Save Logging Settings</button></div><div class="notice" id="settingsNotice"></div></div>

<div class="panel"><div class="systemRow"><div><div class="sectionTitle">Restart RaceSync</div><div class="sub">Software-reboots the ESP32 without disconnecting motorcycle power. The full startup diagnostic LED sequence runs again after reboot.</div></div><button class="btn reboot" id="reboot" onclick="rebootDevice()">Reboot ESP32</button></div><div class="notice" id="rebootNotice"></div></div>

</main><script>
let busy=false,settingsLoaded=false;
function setNotice(id,text,cls=''){const n=document.getElementById(id);n.textContent=text;n.className='notice '+cls}
function fmtTime(s){s=Number(s||0);const m=Math.floor(s/60),r=s%60;return m+':'+String(r).padStart(2,'0')}
async function load(){if(busy)return;try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const x=await r.json(),rec=!!(x.logger&&x.logger.recording),gps=!!(x.gps&&x.gps.validFix),sd=!!(x.storage&&x.storage.ready);const state=document.getElementById('state');state.textContent=rec?'RECORDING':'IDLE';state.className='stateName '+(rec?'ok':'');let d='GPS '+(gps?'ready':'waiting')+' · SD '+(sd?'ready':'not ready');if(rec){d+=' · '+fmtTime(x.logger.recordingSeconds);if(x.logger.currentFile)d+=' · '+x.logger.currentFile}document.getElementById('details').textContent=d;document.getElementById('start').disabled=rec||!gps||!sd;document.getElementById('stop').disabled=!rec;document.getElementById('saveSettings').disabled=rec;document.getElementById('reboot').disabled=rec;if(!settingsLoaded&&x.logger){document.getElementById('startSpeed').value=Number(x.logger.startSpeedKmh||10).toFixed(1);document.getElementById('stopDelay').value=Number(x.logger.stopDelaySeconds||60);settingsLoaded=true}}catch(e){const state=document.getElementById('state');state.textContent='OFFLINE';state.className='stateName bad';document.getElementById('details').textContent='Unable to contact RaceSync';['start','stop','saveSettings','reboot'].forEach(id=>document.getElementById(id).disabled=true)}}
async function command(url,verb){if(busy)return;busy=true;document.getElementById('start').disabled=true;document.getElementById('stop').disabled=true;setNotice('notice',verb+'...','warn');try{const r=await fetch(url,{method:'POST',cache:'no-store'});let x={};try{x=await r.json()}catch(e){}if(!r.ok)throw new Error(x.error||('HTTP '+r.status));setNotice('notice',verb+' successful','ok')}catch(e){setNotice('notice',e.message,'bad')}finally{busy=false;await load()}}
function startLogging(){command('/api/logging/start','Starting manual logging')}
function stopLogging(){if(confirm('Stop the current logging session?'))command('/api/logging/stop','Stopping logging')}
async function saveSettings(){if(busy)return;const start=Number(document.getElementById('startSpeed').value),delay=Number(document.getElementById('stopDelay').value);if(!Number.isFinite(start)||start<1||start>100){setNotice('settingsNotice','Start speed must be between 1 and 100 km/h','bad');return}if(!Number.isInteger(delay)||delay<1||delay>600){setNotice('settingsNotice','Stop delay must be between 1 and 600 seconds','bad');return}busy=true;setNotice('settingsNotice','Saving...','warn');try{const r=await fetch('/api/settings/logging',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({startSpeedKmh:start,stopDelaySeconds:delay})});let x={};try{x=await r.json()}catch(e){}if(!r.ok)throw new Error(x.error||('HTTP '+r.status));document.getElementById('startSpeed').value=Number(x.startSpeedKmh).toFixed(1);document.getElementById('stopDelay').value=x.stopDelaySeconds;setNotice('settingsNotice','Settings saved','ok')}catch(e){setNotice('settingsNotice',e.message,'bad')}finally{busy=false;await load()}}
async function rebootDevice(){if(busy)return;if(!confirm('Reboot RaceSync now? The Wi-Fi connection will disappear briefly while the ESP32 restarts.'))return;busy=true;setNotice('rebootNotice','Rebooting RaceSync...','warn');try{const r=await fetch('/api/reboot',{method:'POST'});let x={};try{x=await r.json()}catch(e){}if(!r.ok)throw new Error(x.error||('HTTP '+r.status));setNotice('rebootNotice','Restart requested. Reconnect when RaceSync Wi-Fi returns.','ok');setTimeout(()=>location.reload(),10000)}catch(e){setNotice('rebootNotice',e.message,'bad');busy=false}}
load();setInterval(load,2000);
</script></body></html>)HTML";
}

void RaceSyncApi::beginWebUiRoute()
{
    _server.on("/", HTTP_GET, [this]() {
        _server.sendHeader("Cache-Control", "no-store");
        _server.send_P(200, "text/html", RACESYNC_UI);
    });

    _server.on("/status", HTTP_GET, [this]() {
        _server.sendHeader("Cache-Control", "no-store");
        _server.send_P(200, "text/html", RACESYNC_STATUS_UI);
    });

    _server.on("/control", HTTP_GET, [this]() {
        _server.sendHeader("Cache-Control", "no-store");
        _server.send_P(200, "text/html", RACESYNC_CONTROL_UI);
    });
}
