Import("env")

import os
import subprocess
from pathlib import Path

project_dir = Path(env.subst("$PROJECT_DIR"))
header_path = project_dir / "include" / "RaceSyncBuildInfo.generated.h"


def git_output(*args):
    try:
        return subprocess.check_output(
            ["git", "-C", str(project_dir), *args],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return ""


commit = git_output("rev-parse", "--short=8", "HEAD")
build_number = git_output("rev-list", "--count", "HEAD")

if not commit:
    commit = os.environ.get("GITHUB_SHA", "unknown")[:8]
if not build_number:
    build_number = os.environ.get("GITHUB_RUN_NUMBER", "0")

dirty = bool(git_output("status", "--porcelain", "--untracked-files=no"))
commit_label = commit + ("-dirty" if dirty else "")

header = f"""#pragma once
// Generated by scripts/generate_build_info.py. Do not edit.
#define RACESYNC_BUILD_NUMBER {int(build_number)}
#define RACESYNC_GIT_COMMIT "{commit_label}"
"""

header_path.parent.mkdir(parents=True, exist_ok=True)
if not header_path.exists() or header_path.read_text(encoding="utf-8") != header:
    header_path.write_text(header, encoding="utf-8")

print(f"[VERSION] RaceSync build {build_number} ({commit_label})")
